import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const FORBIDDEN = /\b(aegis|claude|anthropic|skill|prompt|generated by|dihasilkan oleh AI)\b/i;
const read = (p: string) => readFileSync(p, 'utf8');
function walk(d: string): string[] {
  return readdirSync(d).flatMap((n) => {
    const p = join(d, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

describe('public text', () => {
  it('has no tooling or generation language in pages, ui strings or site constants', () => {
    const files = [...walk('src/pages'), 'src/i18n/ui.ts', 'src/lib/site.ts', 'README.md', 'README.id.md'];
    for (const f of files.filter((f) => /\.(astro|ts|md)$/.test(f))) {
      expect(read(f), f).not.toMatch(FORBIDDEN);
    }
  });
  it('disclaimer is general, not about a single named person', () => {
    const s = read('src/lib/site.ts');
    expect(s).toMatch(/siapa pun yang disebut/);
    expect(s).not.toMatch(/DISCLAIMER =\s*'[^']*Abil/);
  });
});

describe('shared pages are about any pakar, not only Abil', () => {
  it('right of reply addresses every pakar named, in both languages', () => {
    const s = read('src/pages/hak-jawab.astro');
    expect(s).not.toMatch(/Abil/);
    expect(s).toContain('Pakar yang disebut');
    expect(s).toContain('Any expert named');
  });
  it('About states the site purpose and links the method page', () => {
    const s = read('src/pages/tentang.astro');
    expect(s).not.toMatch(/penggagas Operasi Ababil|initiator of the Operation Ababil/);
    expect(s).toContain("routePath('method'");
    expect(s).toMatch(/Kawal Kepakaran/);
  });
  it.each(['src/pages/videos.astro', 'src/pages/tiktok.astro', 'src/pages/buku.astro'])('%s is labelled as Case 001 material', (p) => {
    const s = read(p);
    expect(s).toMatch(/Kasus 001/);
    expect(s).toMatch(/Case 001/);
  });
});
